name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3.5"

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install Busted
        run: luarocks install busted

      - name: Run tests
        run: busted music_theory_spec.lua
